spring.application.name=backend-prjint3-lanchonete
server.port=4001

# Ajuste usuario, senha, host e porta conforme o ambiente.
spring.datasource.url=jdbc:mysql://edumysql.acesso.rj.senac.br:3306/20261_prjint3_manha_felipeespinola?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=latin1
spring.datasource.username=20261_prjint3_manha
spring.datasource.password=senac@13465
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# O projeto foi gerado para usar a estrutura SQL existente.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
